Make modal version
Victoria129/Portfolio pull request #11
Opened 2022-10-13 00:49 UTC by Victoria129

- Design a modal version using JavaScript.

2022-10-13 01:32 UTC, zieeco requested changes
Hi @Victoria129,


Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-13 01:32 UTC, zieeco commented on index.html
> +<!-- End of html for pop up -->
- Hey great job with the pop however, according to the project requirement, you're to create the pop-up dynamically using javascript. please kindly use adjust your implementation to meet the project requirements

2022-10-13 01:32 UTC, zieeco commented on index.html
> +<!-- End of html for pop up -->
- Also, you're to update the project section in the index.htm file by adding them dynamically using javascript. i.e, the HTML structures you have hard coded in the index.html file should no longer be there but created dynamically using javascript. Therefore, these [lines of codes](https://github.com/Victoria129/Portfolio/blob/4958428085c86e937af2aa167f0c40a00a28c42a/index.html#L99-L190) should be added dynamically. please kindly update this to meet the project requirement

2022-10-15 15:01 UTC, tugsem approved these changes
## APPROVED 👍 
Hi @Victoria129 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⭐ 
✔️ You implemented requested changes(Please look optional suggestions 👇 )
## Optional suggestions 🎯 
<h1> As the previous reviewer didn't address these although they are in the project requirements, please fix these issues under the review as they are important for your designing skills. </h1>

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-15 15:01 UTC, tugsem commented on app.js
> +    also the leap into electronic typesetting, remaining essent`,
- [ ] You should add these two example attributes as you are gonna need them in your future job search. (You are going to use different languages and source links for each of your project )
```suggestion
   * technologies: ["Phaser3", "JavaScript", "Jest"],
   * link: "link_to_live_version.com",
```

2022-10-15 15:01 UTC, tugsem commented on style.css
> +}
- [ ]  Please fix these spacing issues on your modal window as they highly effects user experience:
- On window width 375px, your buttons: 
![image](https://user-images.githubusercontent.com/91486791/195992754-9e92dd2c-8d2c-4b0b-ae80-20dd19de3b31.png)

- On window width 503px, your buttons: 
![image](https://user-images.githubusercontent.com/91486791/195992815-9f3f9ac4-e153-4d8f-b806-71bc2cd9cae9.png)
- on 1000px and more, the img goes bigger and card title and padding disappears: 
![image](https://user-images.githubusercontent.com/91486791/195992939-fb95d7a0-8afb-443f-a391-8bba0b406921.png)

2022-10-15 15:21 UTC, merged